# Generated by Django 5.2.13 on 2026-04-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIs", "0005_scanlog_all_probs_scanlog_risk_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="ehr_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="family_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="symptoms",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
