# Generated by Django 5.2.13 on 2026-04-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIs", "0006_patient_blood_group_patient_ehr_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanlog",
            name="is_escalated",
            field=models.BooleanField(default=False),
        ),
    ]
