# Generated by Django 5.2.13 on 2026-04-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIs", "0007_scanlog_is_escalated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scanlog",
            old_name="notes",
            new_name="doctor_notes",
        ),
        migrations.AddField(
            model_name="scanlog",
            name="doctor_validated_disease",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scanlog",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scanlog",
            name="scan_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
