# Generated by Django 5.2.13 on 2026-04-25 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APIs", "0008_rename_notes_scanlog_doctor_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanlog",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
